### ISSUE TITLE
Use environment variables instead of CLI profiles

### ISSUE THREAD

**Issue by aph3rson** [jakejarvis/s3-sync-action#16]
In #1, it's discussed that the action should be using profiles to prevent stomping on other AWS actions which are used by the repo.

However, in [the AWS CLI documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html), it's mentioned that the CLI supports certain environment variables natively. This includes authentication-related variables such as `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY`/`AWS_SESSION_TOKEN`. 

Any reason we're not relying on these instead?

**Comment by alexjurkiewicz** [comment]
AWS publish an action to set up authentication credentials, you can rely on that and remove all profile/key related code:

```yaml
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
```

**Comment by CumpsD** [comment]
Not sure why all of this is present then:

https://github.com/jakejarvis/s3-sync-action/blob/master/entrypoint.sh#L30-L38

https://github.com/jakejarvis/s3-sync-action/blob/master/entrypoint.sh#L47-L56

Seems like that can all be gone when we use the configure-aws-credentials action?

**Comment by CumpsD** [comment]
Which then begs the question, why not remain with just this :)

```
   - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./dist/ s3://<your-website-bucket> --delete
```

**Comment by CumpsD** [comment]
Just verified, this works perfectly:

```
    - name: Configure AWS credentials
      if: github.ref == 'refs/heads/master'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3

    - name: Deploy to S3
      if: github.ref == 'refs/heads/master'
      shell: bash
      run: aws s3 sync ./dist/ s3://$AWS_S3_BUCKET --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
```
