### ISSUE TITLE
Upload failed : An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

### ISSUE THREAD

**Issue by clawfire** [jakejarvis/s3-sync-action#17]
I tried to use your action with this config: 
```
- name: Run AWS Cli to sync content
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: '_site'      # optional: defaults to entire repository
          DEST_DIR: 'deploy_test' # optional: default to bucket root
```
But got this error for every files: 

> upload failed: _site/2019/07/24/ai4eu-the-h2020-initiative-for-a-sovereign-ai-platform-in-europe.html to s3://***/deploy_test/2019/07/24/ai4eu-the-h2020-initiative-for-a-sovereign-ai-platform-in-europe.html An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
