### ISSUE TITLE
Add --acl public-read option

### ISSUE THREAD

**Issue by straumat** [jakejarvis/s3-sync-action#2]
I'm using your action to upload a public website to a S3 bucket. It works fine to upload all the files but the permission of files once uploaded are not public.
Is is possible to add a --acl public-read option ? 
Thanks

**Comment by jakejarvis** [comment]
Great idea. Just in case someone doesn't want to make their bucket readable, you should now be able to specify this in your `.yml` file (using your example from the other issue):

```
      - name: Update website
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: './www/dist/www'
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_S3_BUCKET: ${{secrets.AWS_WWW_S3_BUCKET_STAGING}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
```

You can add any other arguments there too. My bucket must be configured to be public-read by default since I haven't ran into this issue, so let me know if this works for yours if you don't mind! :)
