### ISSUE TITLE
Having an issue finding my SOURCE_DIR

### ISSUE THREAD

**Issue by sean-hill** [jakejarvis/s3-sync-action#30]
Hi there! I'm receiving an error:

```
The user-provided path dist does not exist.
```
As you can see in the screenshot below. You can also see in the screenshot that the `dist` directory does in fact exist after running my build command.

![Screen Shot 2020-05-08 at 10 51 20 AM](https://user-images.githubusercontent.com/1205866/81433721-e4f9af80-9119-11ea-80d1-37442e1d5e87.png)

I believe this may be related to the fact that I have a `working-directory` set as seen in my yml file:

```yml
name: Website

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: merchant-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run test:unit
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build:staging
      - run: ls -gal
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_WEBSITE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'dist'
```

So my `dist` folder would be at `/home/runner/work/paybidet/paybidet/merchant-app/dist` not at `/home/runner/work/paybidet/paybidet/dist`.

Any help would be much appreciated!
