### ISSUE TITLE
"Your workflow file was invalid" error

### ISSUE THREAD

**Issue by freaksauce** [jakejarvis/s3-sync-action#5]
I'm trying to use your action but I get the following error:

`Your workflow file was invalid: .github/workflows/staging.yml (Line: 26, Col: 9): There's not enough info to determine what you meant. Add one of these properties: run, shell, uses, with, working-directory`

I added your action after my current setup so that I can run `npm install` and `npm build` first. Did I do something wrong?

```
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install & build
        run: |
          npm install
          npm run build --if-present
      - name: S3 Sync
      - uses: jakejarvis/s3-sync-action@v0.3.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: './build'
          AWS_REGION: 'ap-southeast-2'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```
