### ISSUE TITLE
AWS_S3_BUCKET is not set. Quitting.

### ISSUE THREAD

**Issue by adam-snetiker** [jakejarvis/s3-sync-action#53]
My AWS bucket is in fact set, but I keep getting this error message so my action won't work to completion. Should I include the static website endpoint instead or in addition to the bucket name? I know the bucket is correct, but it's not being recognized at all. 
<img width="931" alt="Screen Shot 2021-02-03 at 12 09 58 PM" src="https://user-images.githubusercontent.com/78442514/106803455-18ba2500-6619-11eb-98b6-932c082750e5.png">

**Comment by andre-lx** [comment]
Can you paste your step please?

**Comment by aljones15** [comment]
Here are mine:

```bash
  update-s3-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: 'S3 Bucket sync'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} # optional: defaults to us-east-1
          SOURCE_DIR: 'reports'      # optional: defaults to entire repository
```

getting the same error

error is coming from here: https://github.com/jakejarvis/s3-sync-action/blob/7ed8b112447abb09f1da74f3466e4194fc7a6311/entrypoint.sh#L5-L8

**Comment by andre-lx** [comment]
Hi @aljones15.

I have the same configuration as you. 

Can you try to set manually the bucket name in the action?

It looks like the secret is not being pulled.

**Comment by aljones15** [comment]
did that now getting: AWS_ACCESS_KEY_ID is not set. Quitting.

yeah this is weird. any idea why the secrets are not showing up?
They are definitely set.

```
  update-s3-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: 'S3 Bucket sync'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: 's3://vaxcert-interop-reports'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} # optional: defaults to us-east-1
          SOURCE_DIR: 'reports'      # optional: defaults to entire repository
~                                                                                  
```

The secrets are set as `Environment secrets` perhaps they need to be `Repository secrets` or `Organization secrets`?

**Comment by andre-lx** [comment]
Not a clue. But it's definitely something with your secrets. 

Try to delete the secrets and add it again. Are you using organisational secrets or repository ones? Try on the repo itself.

**Comment by aljones15** [comment]
Thank you for the help. I was using environment secrets. I think the issue with those was that I was not telling it what environment to use. Using the repo level secrets did work, but now it can't find the dir I want to sync with the bucket.

**Comment by andre-lx** [comment]
The `reports` dir? What error did you get now?

**Comment by aljones15** [comment]
```
The user-provided path ./reports does not exist.
```

I checked and I seem to be in an empty docker container, not sure how to get the dir that results from the test run to be available to the aws cli docker.

```
name: Node.js CI
  
on: [push]
  
jobs:
  test-node: 
    runs-on: ubuntu-latest
    timeout-minutes: 35
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Run test with Node.js ${{ matrix.node-version }}
        run: npm run test-node
        continue-on-error: true
  update-s3-bucket:
    runs-on: ubuntu-latest
    needs: [test-node]
    steps:
      - name: 'Dir check'
        run: ls -la
      - name: 'S3 Bucket sync'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: 's3://vaxcert-interop-reports'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} # optional: defaults to us-east-1
          SOURCE_DIR: './reports'      # optional: defaults to entire repository
```
