### ISSUE TITLE
Doesn't seem to Support MacOS

### ISSUE THREAD

**Issue by zackrspv** [jakejarvis/s3-sync-action#54]
This doesn't seem to support MacOS, the runner retuns: 

```
Run jakejarvis/s3-sync-action@master
  with:
    args: --acl public-read --delete
  env:
    ImageOS: macos1015
    AWS_S3_BUCKET: 
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_REGION: ***
    SOURCE_DIR: ./Home/Android/Releases/
```
**Error: Container action is only supported on Linux**

**Comment by okalachev** [comment]
macOS workers include AWS-CLI, so uploading can be performed with a raw command like this:

```yaml
- name: Upload
  run: AWS_ACCESS_KEY_ID=${{secrets.S3_KEY}} AWS_SECRET_ACCESS_KEY=${{secrets.S3_SECRET_KEY}} aws s3 sync . s3://<bucket-name>/ --acl public-read --no-progress
  working-directory: <directory-to-sync>
```
