### ISSUE TITLE
Is it possible to get the creator of this GH Action verified in the marketplace?

### ISSUE THREAD

**Issue by javsalgar** [jakejarvis/s3-sync-action#67]
My organization is now enforcing to use actions by verified creators. I'd love to use this action but I see that right now it is not verified. Any chance that this could happen?

**Comment by markstos** [comment]
The workaround is to use a container which provides the `aws` binary:

```yaml
- name: Sync to S3
  run: >
    aws s3 sync
    ./docs
    s3://${{ secrets.DOC_AWS_S3_BUCKET }}/
    --acl public-read --follow-symlinks --delete

  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: 'us-east-1'
```

Your pipeline may be simpler and run faster with one less Github Actions container to boot!
