### ISSUE TITLE
using path outside of ./

### ISSUE THREAD

**Issue by y-nk** [jakejarvis/s3-sync-action#77]
I'm having a simple action which does:

```yml
- name: Create dummy
  run: |
    mkdir /tmp/foo
    echo "foobar" > /tmp/foo/bar

- name: Upload on S3
  uses: jakejarvis/s3-sync-action@v0.5.1
  with:
    args: --acl public-read --follow-symlinks
    env:
      AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SOURCE_DIR: /tmp/foo
      DEST_DIR: /baz
```

and i get an error thrown: `"The user-provided path /tmp/foo does not exist"`.

Could it be related to `/tmp` not being mounted (since it's a docker action)? Anybody else having this issue? Aside from "use a different path", any other idea for a workaround?
